### ISSUE TITLE
The sql dump file does not exist.

### ISSUE THREAD

**Issue by ejmurray** [xmetdb/xmetdb-docs#1]
I can't download the dump file.

**Comment by egonw** [comment]
I will check the link in the wiki, but did you try it from this page? https://figshare.com/articles/xmetdb-20160815_sql/3581199/1

**Comment by egonw** [comment]
@ejmurray I checked the link on the wiki page (http://www.xmetdb.org/wiki/Main_Page). Can you please let me know the location of the broken link to the SQL dump?

**Comment by ejmurray** [comment]
It is this link
http://pele.farmbio.uu.se/dl/xmetdb-mysql-20160801.dump

**Comment by olas** [comment]
Fixed now.

**Comment by ejmurray** [comment]
Thanks.
